### ISSUE TITLE
Could not load file or assembly 'AngleSharp, Version=0.16.0.0

### ISSUE THREAD

**Issue by MaceWindu** [AngleSharp/AngleSharp.Css#103]
# Bug Report

## Description

AngleSharp.Css (0.16.3 and current master) built against AngleSharp 0.16.0 ([see here](https://github.com/AngleSharp/AngleSharp.Css/blob/devel/src/AngleSharp.Css/AngleSharp.Css.csproj#L24)), but nuspec dependency bumped to [0.16.1](https://github.com/AngleSharp/AngleSharp.Css/blob/devel/src/AngleSharp.Css.nuspec#L17).

This results in error in
```
System.IO.FileLoadException: 'Could not load file or assembly 'AngleSharp, Version=0.16.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
```
in .net framework programs without binding redirect.

## Steps to Reproduce

- create netfx project
- reference anglesharp.css 0.16.3 nuget
- create instance of e.g. `CssParser`
- run program

**Expected behavior:** it works

**Actual behavior:** it crashes due to dependent assembly version mismatch

**Environment details:** .net framework 4.8

## Possible Solution

New release built against AngleSharp 0.16.1

**Comment by FlorianRappl** [comment]
PR welcome.

**Comment by MaceWindu** [comment]
#104
