### ISSUE TITLE
Unable to use new UseHex property as it is in an internal structure

### ISSUE THREAD

**Issue by a-teece** [AngleSharp/AngleSharp.Css#105]
The new UseHex property is a great idea, but it can't easily be used as the Structure is internal.

I assume the unit tests are passing because they have access to internal classes/structs/etc.

We're working around using reflection to set it for now, but a fix would be nice.

It would still be nice to disable all colour normalisation given the popularity of AngleSharp and the problems RGBA causes for Outlook - a pretty common use-case in the wild.

We're hoping that UseHex is a good-enough fix for now

**Comment by a-teece** [comment]
> 

Sorry for not responding, I didn't just ignore the request, Shesh is a member of our team at Enate who was closer to the original CSS problem so I asked him to help get this over the line.

**Comment by FlorianRappl** [comment]
Great - thanks for the heads up!
