### ISSUE TITLE
Color not parsed correctly if rgb is not all lowercase

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp.Css#109]
```c#
var html = @"<p style='color: RGB(0,17,0)'>Text</p>";
var parser = new HtmlParser(new HtmlParserOptions(), BrowsingContext.New(Configuration.Default.WithCss(new CssParserOptions())));
var dom = parser.ParseDocument(html);
var p = dom.QuerySelector("p");
var s = p.GetStyle();
var color = s.GetColor(); // -> ""
```

Perhaps this occurs because the dictionary here does not use a comparer that ignores case:

https://github.com/AngleSharp/AngleSharp.Css/blob/248a870ada17083c4a2aee2dc00f97a448b12c9b/src/AngleSharp.Css/Parser/Micro/ColorParser.cs#L11-L20

This was originally reported as https://github.com/mganss/HtmlSanitizer/issues/340.

**Comment by FlorianRappl** [comment]
It's a good point. Right now everything is case insensitve, but actually function names (and color names) should be case sensitive:

See https://www.w3.org/TR/css-color-4/#resolving-sRGB-values.

**Comment by mganss** [comment]
Isn't it the other way around, i.e. it should be case insensitive (`rgb` and `RgB` are treated the same, case is ignored) and currently it's case sensitive (only lowercase works)?

**Comment by FlorianRappl** [comment]
> Isn't it the other way around, i.e. it should be case insensitive (rgb and RgB are treated the same, case is ignored) and currently it's case sensitive (only lowercase works)?

Correct(ed) - that's what I meant.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
