### ISSUE TITLE
Incompatible with AngleSharp 1.0.0

### ISSUE THREAD

**Issue by Darkar25** [AngleSharp/AngleSharp.Css#110]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [ ] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

When running the application i get the following exception:

ReflectionTypeLoadException: Unable to load one or more of the requested types. Method 'get_BaseUrl' in type 'AngleSharp.Css.Dom.PseudoElement' from assembly 'AngleSharp.Css, Version=0.16.4.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea' does not have an implementation.

There is a workaround however: Downgrade AngleSparp to 0.16.1

## Steps to Reproduce

1. Install latest AngleSharp version
2. Install latest AngleSharp.Css release
3. Run application
4. Get error

**Expected behavior:** Work normally

**Actual behavior:** Runtime exception

**Environment details:** Win10, .NET 6.0

**Comment by FlorianRappl** [comment]
There is no AngleSharp 1.0.0. The latest version (released today) is 0.17.0 The version before that was 0.16.1
