### ISSUE TITLE
Make Parser Classes Public

### ISSUE THREAD

**Issue by jbienzms** [AngleSharp/AngleSharp.Css#111]
# New Feature Proposal

## Description

I would like to parsing related types made public. Most of them can be found in the [Parser](https://github.com/AngleSharp/AngleSharp.Css/tree/main/src/AngleSharp.Css/Parser) folder.

## Background

I'm working on a sample application that can load [A-Frame](https://aframe.io/) content. The attribute syntax for A-Frame [Multi-Property components](https://aframe.io/docs/1.3.0/core/component.html#multi-property-component) conforms to CSS guidelines. Therefore, I'd like to use AngleSharp classes like [IdentParser](https://github.com/AngleSharp/AngleSharp.Css/blob/devel/src/AngleSharp.Css/Parser/Micro/IdentParser.cs) to parse the values stored in these attributes. Unfortunately, since the types in this folder do not have an explicit access modifier, they're defaulting to Internal and are not public.

## Specification

I do not believe that making these parser classes public would have an impact on any the spec.

**Comment by FlorianRappl** [comment]
Landed in `devel`
