### ISSUE TITLE
.GetInnerText() NullReferenceException

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp.Css#118]
# Bug Report
**NullReferenceException** at AngleSharp.Css.FeatureValidators.WidthFeatureValidator.**Validate(...)**
when trying call GetInnerText() in HtmlAnchorElement on this piece of code example: attached file href.txt
[href.txt](https://github.com/AngleSharp/AngleSharp.Css/files/9691072/href.txt)

document.QuerySelector( "a[href]" ).GetInnerText()

**Comment by FlorianRappl** [comment]
I think you did not provide a `RenderDevice` as mentioned in the docs (https://github.com/AngleSharp/AngleSharp.Css#basic-configuration).

Unfortunately you don't provide much info - so I can't tell.
