### ISSUE TITLE
ToCss produces unescaped selectors

### ISSUE THREAD

**Issue by MartinWelsch** [AngleSharp/AngleSharp.Css#119]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [ ] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description
The `ToCss` method writes unescaped characters which results in invalid CSS.
Consider the following program:
```cs
using System;
using AngleSharp;
using AngleSharp.Css.Parser;

public class Program
{
	public static void Main()
	{
		var p = new CssParser();
		var s = p.ParseStyleSheet(@".-\\ { color: magenta; }");
		Console.WriteLine(s.ToCss());
		
		// This prints:
		// .-\ { color: rgba(255, 0, 255, 1) }
	}
}
```

At first a small CSS stylesheet is parsed: `.-\\ { color: magenta; }`. The selector contains a backslash which has to be escaped using another backslash (this applies for all characters other than `[0-9a-zA-Z\-_]`).

However if the parsed stylesheet is converted back to text using `ToCSS` the backslash is not escaped. The resulting text is not valid CSS.

This behaviour is not constrained to the `\`! Tested characters:
`.-\$ { color: magenta; }` becomes `.-$ { color: magenta; }`
`.-\@ { color: magenta; }` becomes `.-@ { color: magenta; }`
`.-\! { color: magenta; }` becomes `.-! { color: magenta; }`

**Expected behavior:** `ToCSS` should produce `.-\\ { color: rgba(255, 0, 255, 1) }`

**Actual behavior:** `ToCSS` produced `.-\ { color: rgba(255, 0, 255, 1) }`

**Environment details:** .NET6, AngleSharp 0.17.1, AngleSharp.Css 0.16.4

## Possible Solution
Since [`CssStyleRule`](https://github.com/AngleSharp/AngleSharp.Css/blob/f85b2f658b31da07fd56489c5a470bf7502b0be1/src/AngleSharp.Css/Dom/Internal/Rules/CssStyleRule.cs) calls the [`CssStyleFormatter`](https://github.com/AngleSharp/AngleSharp/blob/3a21e4c65b53dbd53d35dee4b1f692659a7f535e/src/AngleSharp/Css/CssStyleFormatter.cs) like this: `writer.Write(formatter.Rule(SelectorText, null, block));`

`CssStyleFormatter` should escape incoming rule names instead of just passing them here:
```cs
String IStyleFormatter.Rule(String name, String prelude, String rules) => String.Concat(/*the name is still unescaped*/name, " ", String.IsNullOrEmpty(prelude) ? String.Empty : prelude + " ", rules);
```
change to this (the first (`.`) and second character have to be valid):
```cs
String IStyleFormatter.Rule(String name, String prelude, String rules) => String.Concat(name.Length > 2 ? String.Concat(name.Substring(0, 2), CssUtilities.Escape(name.Substring(2))) : name, " ", String.IsNullOrEmpty(prelude) ? String.Empty : prelude + " ", rules);
```

or pass the responsibility of escaping to the callers since this is just a formatter after all

**Comment by FlorianRappl** [comment]
Happy to receive PRs on this one.
