### ISSUE TITLE
NullReferenceException in `ToCss()`

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp.Css#129]
```c#
var html = "<div style=\"border-width:1px;border-right-width:px;\"></div>";
var parser = new HtmlParser(new HtmlParserOptions(), BrowsingContext.New(Configuration.Default.WithCss(new CssParserOptions())));
var dom = parser.ParseDocument(html);
var div = dom.Body?.FirstElementChild;
var style = div.GetStyle();
var css = style.ToCss(); // -> exception
```

AngleSharp.Css version is 0.17.0.

The combination of property values has to be very specific to trigger the issue. This does not occur if only `border-right-width:px` is given or `border-right-width:1px;border-right-width:px`.

This was initially reported as https://github.com/mganss/HtmlSanitizer/issues/426.

**Comment by FlorianRappl** [comment]
Fixed and will be part of next preview / release (1.0.0).
