### ISSUE TITLE
Any plan to publish a version compatible with Anglesharp 1.0.1

### ISSUE THREAD

**Issue by meziantou** [AngleSharp/AngleSharp.Css#130]
The latest version of `AngleSharp.Css` supports `AngleSharp` `>= 0.17.0` and `< 0.18.0`. So, the following combination cannot be restored:

````
    <PackageReference Include="AngleSharp" Version="1.0.1" />
    <PackageReference Include="AngleSharp.Css" Version="0.17.0" />
````

Is there a plan to publish a new version of `AngleSharp.Css` compatible with the latest version of `AngleSharp`?

**Comment by FlorianRappl** [comment]
Eventually yes, but the backlog is long and contributors / sponsors are rare. So unless the project gets more contributors or sponsors there won't be such a release.

**Comment by meziantou** [comment]
Is fixing the breaking changes and the failing tests enough, or do you plan to include other changes in the v1 release?

**Comment by FlorianRappl** [comment]
https://github.com/AngleSharp/AngleSharp.Css/milestone/2

**Comment by meziantou** [comment]
Thanks for the details! I'll close this issue as there is already a way to track progress.
