### ISSUE TITLE
Output hex color value for transparent values if `UseHex` is true

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp.Css#132]
Currently, when `UseHex` is true, color values are output as hex only if alpha is 1.0.

https://github.com/AngleSharp/AngleSharp.Css/blob/15deaee3586d4c37d0054bc80d579ed70f7c74f6/src/AngleSharp.Css/Values/Primitives/Color.cs#L376-L381

https://github.com/AngleSharp/AngleSharp.Css/blob/15deaee3586d4c37d0054bc80d579ed70f7c74f6/src/AngleSharp.Css/Values/Primitives/Color.cs#L398-L401

Perhaps this could be changed to include colors with alpha < 1.0, too.

**Comment by FlorianRappl** [comment]
Implemented and available in next preview / 1.0.0.

**Comment by mariusz96** [comment]
@FlorianRappl Should `CssColorValue` docs be updated to reflect the change?
https://github.com/AngleSharp/AngleSharp.Css/blob/devel/src/AngleSharp.Css/Values/Primitives/CssColorValue.cs#L466-L471
