### ISSUE TITLE
Detected package version outside of dependency constraint: AngleSharp.Css 0.17.0 requires AngleSharp (>= 0.17.0 && < 0.18.0) but version AngleSharp 1.0.1 was resolved.

### ISSUE THREAD

**Issue by mediabuff** [AngleSharp/AngleSharp.Css#139]
Hi, why is this still tied to old versions of AngleSharp. I get the above message in Visual Studio

**Comment by FlorianRappl** [comment]
It's not a bug (not sure why you think that?).

Right now there is no time to make AngleSharp.Css compatible with AngleSharp v1. You can help by making contributions - either to code or via the sponsorship.
