### ISSUE TITLE
CssSkewValue, CssTranslateValue, CssRotateValue, CssScaleValue are non-public.

### ISSUE THREAD

**Issue by cyraid** [AngleSharp/AngleSharp.Css#142]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Title pretty much says it all. Crawling through the KeyFrames and using ParseTransform. I have access to the "Arguments", but took awhile that for the 'degree' of rotate for example, was in the 4th argument, because it was part of a class I had no idea what was in it. To prevent future incompatibility it would be easier just to use the classes directly incase something changes.

## Possible Solution

Put public infront of each class. :)

**Comment by FlorianRappl** [comment]
They are non-public on purpose until the CSSOM is implemented and their API is adjusted / figured out.

See #38 and #6.
