### ISSUE TITLE
Copatibility with AngleSharp.Core >= 1.0.0

### ISSUE THREAD

**Issue by truthz03** [AngleSharp/AngleSharp.Css#145]
Hi,

is there a plan to support newer AngleSharp.Core packages?
AngleSharp 0.17.1 has some bugs or missing features wich will be fixed with 0.17.2 (I tested my code with the AngleSharp.Core source code and the last commit before 1.0.0 which has the version 0.17.2) but 0.17.2 was not released as Nuget.
The next release after 0.17.1 is 1.0.0 but AngleSharp.Css needs < 0.18

Thanks,
Thomas

**Comment by FlorianRappl** [comment]
Yes there is - see the 1.0.0 milestone.
