### ISSUE TITLE
Dependency on AngleSharp < 0.18.0

### ISSUE THREAD

**Issue by tomas-net** [AngleSharp/AngleSharp.Css#147]
AngleSharp.Css NuGet package depends on AngleSharp >= 0.17.0 && **< 0.18.0**

Is there any valid reason for limitation **< 0.18.0**? Latest version of AngleSharp is 1.0.2. AngleSharp 0.17.1 was updated directly to 1.0.0

**Comment by FlorianRappl** [comment]
The limitation is because its incompatible.
