### ISSUE TITLE
NullReference exception when invoking GetStyle() in configuration without CSS

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp.Css#15]
Example:
```C#
// no .WithCss() here!
var p = new HtmlParser(new HtmlParserOptions(), BrowsingContext.New(new Configuration()));
var dom = p.ParseDocument(@"<html><body><div style=""color: black"">Test</div></body></html>");
var div = dom.QuerySelector("div");
var style = div.GetStyle(); // NullReferenceException
```

I believe this occurs here: https://github.com/AngleSharp/AngleSharp.Css/blob/c99d5d782bb5f248c69631917e4f955d843a65b3/src/AngleSharp.Css/Dom/Internal/CssStyleDeclaration.cs#L112

**Comment by FlorianRappl** [comment]
Hm what do you expect here?

I mean you clearly use an extension method that *should* only be available when you have CSS activated. Should another exception appear? What is the behavior you want to see here.

Just to be clear: The call is definitely wrong (i.e., it would not even exist if you did not reference AngleSharp.Css) so imho the only result can be an exception. Silently failing (e.g., returning null) is not an option here.

**Comment by mganss** [comment]
Fair enough, feel free to close this issue. In AngleSharp 0.9 the `Style` property returned null in this case. Perhaps a different exception should occur (NotSupportedException?), but that's just nitpicking 😄

**Comment by FlorianRappl** [comment]
Hm after visiting the code I am not sure anymore @mganss. Apparently, if there is a problem with the declaration it is also silently ignored. So I would say we should do the same as if an invalid declaration has been found (which returns `null`). Would that be alright with you, too?

**Comment by mganss** [comment]
Sure 👍

**Comment by FlorianRappl** [comment]
Landed in `devel`.
