### ISSUE TITLE
Is stable release compatible with latest AngleSharp 1.x?

### ISSUE THREAD

**Issue by egil** [AngleSharp/AngleSharp.Css#150]
I see that version 0.17 list compatibility with AngleSharp 0.17 to 0.18 on NuGET? Does this mean I have to stay with 0.18 of AngleSharp if I need a stable version of AngleSharp.CSS for now?

**Comment by FlorianRappl** [comment]
Yes - unless we get more contributors or funding for AngleSharp.Css we will have a hard time releasing a 1.0 here (backlog still has too many items before we can get a 1.0 released).

There is a pre-release of AngleSharp.Css that you can use. It is unlikely that the pre-release will have (significant) breaking changes, it is just not feature complete yet.

**Comment by egil** [comment]
I understand lack of time all to well when it comes to OSS.

Do you have a complete list of need-to-have issues/features for anglesharp.css to be done?

**Comment by FlorianRappl** [comment]
The list is everything associated with the v1 milestone: https://github.com/AngleSharp/AngleSharp.Css/milestone/2

Items that are bugs are generally the highest prio, with enhancements having a lower prio (the `cssom` items in there need to be in v1 for sure). The documentation item would have the lowest prio even though I personally would rate it quite high (but people seem to be fine with the amount of documentation, so it would not be wild to just keep it as-is).

**Comment by FlorianRappl** [comment]
Now on track to release a v1. Should be done this week / in January. Then I can release a 1.0 of `AngleSharp.Diffing`.

**Comment by vinaykapadia** [comment]
> Now on track to release a v1. Should be done this week / in January. Then I can release a 1.0 of `AngleSharp.Diffing`.

Has this been done yet?

**Comment by egil** [comment]
> > Now on track to release a v1. Should be done this week / in January. Then I can release a 1.0 of `AngleSharp.Diffing`.
> 
> 
> 
> Has this been done yet?

Anglesharp.Diffing has been released in v1 with support for latest Anglesharp.css included.

**Comment by vinaykapadia** [comment]
Thanks!
