### ISSUE TITLE
AngleSharp css dependency

### ISSUE THREAD

**Issue by adhavanv** [AngleSharp/AngleSharp.Css#154]
# Bug Report
When i get AngleSharpCss 1.0.0-alpha-99 package,it contains 0.17 version

![image](https://github.com/AngleSharp/AngleSharp.Css/assets/58745328/c852197c-7e37-47c5-b623-5dbf73b21260)

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [Yes ] Are you running the latest version of AngleSharp?
- [ ] Did you check the FAQs to see if that helps you?
- [ ] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [ ] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description
When i get AngleSharpCss 1.0.0-alpha-99 package,it contains 0.17 version
[Description of the bug]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Environment details:** [OS, .NET Runtime, ...]

## Possible Solution

[Optionally, share your idea to fix the issue]
![image](https://github.com/AngleSharp/AngleSharp.Css/assets/58745328/7551d973-5d15-40f7-873f-e0cdbfb144d8)
![anglesharp](https://github.com/AngleSharp/AngleSharp.Css/assets/58745328/3f38ab15-8416-4b6d-9108-466cdae11144)

**Comment by FlorianRappl** [comment]
What you have is the actual pre-release of AngleSharp.Css 1.0.0.
