### ISSUE TITLE
AngleSharp dependency issue in .NET Framework (IIS-hosted WCF service)

### ISSUE THREAD

**Issue by qwerty-debug** [AngleSharp/AngleSharp.Css#170]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp.Css?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Xml` for Xml support)
- [X] Did you perform a search in the issues?

### Description

[NuGet](https://www.nuget.org/packages/AngleSharp.Css/#dependencies-body-tab) shows the following dependency:
[AngleSharp](https://www.nuget.org/packages/AngleSharp/) (>= 0.17.0 && < 0.18.0)
This suggests that either [0.17.0](https://www.nuget.org/packages/AngleSharp/0.17.0) or [0.17.1](https://www.nuget.org/packages/AngleSharp/0.17.1) would be OK.

Building with AngleSharp 0.17.1 works fine when starting a project from VS in debug mode, but once published to a server it results in the following exception:
System.IO.FileLoadException: Could not load file or assembly 'AngleSharp, Version=0.17.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea' or one of its dependencies.

Assembly Binding Log:
[AngleSharp, Version=0.17.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea.HTM.txt](https://github.com/AngleSharp/AngleSharp.Css/files/15176709/AngleSharp.Version.0.17.0.0.Culture.neutral.PublicKeyToken.e83494dcdc6d31ea.HTM.txt)

Related:
https://github.com/mganss/HtmlSanitizer/issues/544

### Steps to Reproduce

Start a .NET framework project.
Add a NuGet package that depends on both AngleSharp 0.17.1 and AngleSharp.Css 0.17.0 (e.g. HtmlSanitizer).
Write some code that triggers assembly binding on AngleSharp.CSS + dependencies.
Publish code to server.
Trigger code.

### Expected Behavior

Assemblies bind correctly and the code executes.

### Actual Behavior

Code does not execute due to an assembly binding error.

### Possible Solution / Known Workarounds

Workaround: download projects from GitHub and build from source instead of relying on NuGet.

**Comment by FlorianRappl** [comment]
Unfortunately older versions are not supported; we are currently at AngleSharp 1.x and only supporting that. Due to time constraints there cannot be any support for 0.x versions.

**Comment by qwerty-debug** [comment]
AngleSharp.Css 1.x is still in beta...
is the latest non-beta release considered 'an older version'?

**Comment by qwerty-debug** [comment]
For future reference: the issue can be resolved by including binding redirects in Web.config.
Depending on how the project for hosting WCF services in IIS is set up these binding redirects might or might not be autogenerated by VS.
