### ISSUE TITLE
Class duplication in AndleSharp and AngleSharp.Css prevents using IlMerge

### ISSUE THREAD

**Issue by PavelFischerCoupa** [AngleSharp/AngleSharp.Css#173]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp.Css?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Xml` for Xml support)
- [X] Did you perform a search in the issues?

### Description

Hello,

In our project we use `IlMerge` and `AngleSharp` +`AngleSharp.Css`. Both have the same class `AngleSharp.Dom.ElementExtensions` which prevents merging of dlls into single one in the latest version and we are stick to some old version.
Can we move `AngleSharp.Dom.ElementExtensions` from `AngleSharp.Css` library to the `AngleSharp.Css.Dom.ElementExtensions` namespace to avoid name collision?

Kind regards,
Pavel Fischer

### Steps to Reproduce

Use IlMerge to merge dlls

### Expected Behavior

There is n name collision

### Actual Behavior

There is a name collision in `AngleSharp.Dom.ElementExtensions`

### Possible Solution / Known Workarounds

Solution: move `AngleSharp.Dom.ElementExtensions` from `AngleSharp.Css` library to the `AngleSharp.Css.Dom.ElementExtensions` namespace

**Comment by FlorianRappl** [comment]
As this would be a breaking change we don't want to that.

The same namespace has been used on purpose. If you want to use ILMerge on these assemblies, maybe just change the respective class yourself? Overall, I think this is rather an issue with ILMerge - using the same namespace is totally valid and in this case the classes can just be merged, too. There shouldn't be any restrictions like that (especially in the current scenario).

Feel free to open a PR (even here), but this would not be merged until a v2 / we'd anyway make breaking changes.
