### ISSUE TITLE
Conflict Between HtmlSanitizer and Bunit Due to AngleSharp Version

### ISSUE THREAD

**Issue by HarshitDubey-Raik** [AngleSharp/AngleSharp.Css#175]
### Description

I am encountering a version conflict while writing unit tests using Xunit in C#. I have a project named Test which references another project named Worker. The Worker project includes HtmlSanitizer.
In the Test project, I need to install Bunit, which requires AngleSharp version >= 1.1.2.

This version mismatch is causing conflicts, and I am unable to resolve this dependency issue.

Following is the error being displayed while installing
```csharp
Version conflict detected for AngleSharp. 
Install/reference AngleSharp 1.1.2 directly to project Tests to resolve this issue. 
Tests -> bunit 1.30.3 -> bunit.web 1.30.3 -> AngleSharp (>= 1.1.2) 
Tests -> Worker -> HtmlSanitizer 8.0.865 -> AngleSharp (= 0.17.1).
```

After researching I got to know that the problem arises because HtmlSanitizer uses AngleSharp.Css to process CSS. Currently, the HtmlSanitizer 8.0.690-beta depends on AngleSharp.Css 1.0.0-alpha-99, which can be used with AngleSharp 1.0. 

However, since my application is in production, I cannot use this beta version. Could you please let me know when the proper release of the upgraded AngleSharp.Css version is expected so that accordingly HtmlSanitizer can be updated?

Thank you!

**Comment by FlorianRappl** [comment]
> However, since my application is in production, I cannot use this beta version. 

Why?

> Could you please let me know when the proper release of the upgraded AngleSharp.Css version is expected so that accordingly HtmlSanitizer can be updated?

Right now there are no sponsors, so the project is on hold. There is no timeline for releasing the 1.0.0 of AngleSharp.Css.

If you rely on AngleSharp in your production code then maybe you should consider sponsoring it.
