### ISSUE TITLE
How to translate code to AngleSharp 0.11.0

### ISSUE THREAD

**Issue by Sicos1977** [AngleSharp/AngleSharp.Css#19]
Hi,

I'm upgrading code to make use of AngleSharp 0.11.0.

The only thing I can't seem to figure out is how to change this code

```
            return new HtmlParser(new Configuration().WithCss(e => e.Options = new CssParserOptions
            {
                IsIncludingUnknownDeclarations = true,
                IsIncludingUnknownRules = true,
                IsToleratingInvalidConstraints = true,
                IsToleratingInvalidValues = true
            }));
```

I already tried this but have no idea how to do it in 0.11

```
            var options = new HtmlParserOptions();
            var cssParserOptions = new CssParserOptions
            {
                IsIncludingUnknownDeclarations = true,
                IsIncludingUnknownRules = true,
                IsToleratingInvalidSelectors = true
            };

            return new HtmlParser(new Configuration().WithCss() )

```

**Comment by FlorianRappl** [comment]
Any reason for not using the `BrowsingContext`?

(I first want to understand why you follow that route before I suggest a specific solution)

**Comment by Sicos1977** [comment]
I don't know. I just tried to use HtmlSanitizer (https://github.com/mganss/HtmlSanitizer) in my own project that uses AngleSharp 0.11

**Comment by FlorianRappl** [comment]
As far as I know `HtmlSanitizer` won't work with 0.10 / 0.11 - so I would not recommend mixing versions there (could still be done with a binding redirect, but I would, unfortunately, recommend using the lowest version there - unless you have strong reasons for going with 0.11 in your project).

**Comment by Sicos1977** [comment]
Well I fixed all the code to make use of 0.11 but I couldn't figure out how to do the new HtmlParser... so that started this thread.

**Comment by FlorianRappl** [comment]
So you are working on updating `HtmlSanitizer` to 0.11?

The `HtmlParser` was unchanged - only redundant parts of the constructor overload have been removed. If you want to create a parser instance with a `Configuration` just pass the `Configuration` in a `BrowsingContext`. A `BrowsingContext` holds the full instance and gives you access to all registered services. It is the main object you should deal with.

**Comment by FlorianRappl** [comment]
If this issue is solved with the migration docs (see https://github.com/AngleSharp/AngleSharp/blob/master/doc/Migration.md#html) then I would close it. Otherwise, please advise what would be a good addition to the guide.

Thanks!
