### ISSUE TITLE
Question: Replace font

### ISSUE THREAD

**Issue by Sicos1977** [AngleSharp/AngleSharp.Css#22]
Is there an easy way in the latest version of AngleSharp to replace a font in a style with another font?

**Comment by FlorianRappl** [comment]
AngleSharp does not contain any CSS capabilities - hence I transferred this issue to AngleSharp.Css.

Yes, AngleSharp.Css implements the standard DOM APIs for the CSSOM. Thus you could, e.g., use `style.SetFont("NewFont")` when `style` refers to your CSS style declaration. Note: All these setters are extension methods.

HTH!

**Comment by Sicos1977** [comment]
Thanks that is exactly what I needed.

Is there also an easy way to select all the CSS styles? With xpath or something like that? I'm a noob with things like this.

**Comment by FlorianRappl** [comment]
Unfortunately not directly. It also depends - do you mean

- all styles of a stylesheet
- all inline / element styles

If its just about the latter you can do

```cs
document.All
  .Select(m => m.GetStyle())
  .Where(style => style?.GetFont() != null)
  .ForEach(style => style.SetFont("NewFont"));
```

(Remark: `ForEach` may not exist as an extension method - but its easy to write or replace with a `foreach` construct.)

In the stylesheet the situation is a little bit more complicated; here we essentially need to traverse the rules and collect all style rules + descend in the rules containing child rules (e.g., media). Maybe we can add a helper in AngleSharp.Css for this.

**Comment by FlorianRappl** [comment]
Landed in `devel`.

You can now do

```cs
document.All.SetStyle(style => style.SetFont("NewFont"));
```
