### ISSUE TITLE
Expansion of shorthand properties to longhand

### ISSUE THREAD

**Issue by atlastodor** [AngleSharp/AngleSharp.Css#23]
Hi,

I am trying to use AngleSharp.Css 0.10. Most things work fine, however, I've stumbled upon one issue.

Normally, shorthand properties expand correctly, for example:
border-color: red =>
- border-left-color: red;
- border-top-color: red;
- border-right-color: red;
- border-bottom-color: red;

border: 1px solid red =>
- border-width: 1px;
- border-style: solid;
- border-color: red;

This is all OK. But what does not work is recursive expansion into longhand properties. I would expect setting *border* to result in *border-width* *border-style* and *border-color* (as it does), as well as *border-X-width* *border-X-style* and *border-X-color*

Is there a quick way to fix this? And is there some reflection API figure out that *border-width* expands into *border-X-width*?

Thanks,
-Todor

**Comment by FlorianRappl** [comment]
Fix landed in `devel`.
