### ISSUE TITLE
Make ICssFunctionValue public

### ISSUE THREAD

**Issue by MaceWindu** [AngleSharp/AngleSharp.Css#24]
### Description

I'm trying to migrate to latest version and finally try to implement urls extraction from css without changes to AngleSharp itself (see #10). Looks like only missing part is unavailability of `ICssFunctionValue`  interface, implemented by `UrlReference`

### Background

I need to find all url's in css file, specified using 'url()' function.

**Comment by FlorianRappl** [comment]
This interface (like the full CSSOM) will be exposed soon. Its just not stable yet.

I'll leave it open for now, but this is on the roadmap and was communicated as such.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
