### ISSUE TITLE
Question: why SrcDeclaration uses AnyValueConverter?

### ISSUE THREAD

**Issue by MaceWindu** [AngleSharp/AngleSharp.Css#25]
I'm trying to find url function calls and because `@font-face{ src }` uses AnyValue, I cannot detect urls there.
I can only detect `src` property, but it is not very usefull, as `@font-face` src value is a comma-separated list of url/format/local function combinations.

**Comment by MaceWindu** [comment]
Managed to workaround it with following converter. It doesn't parse local/format as functions as I'm not interested in their values.

```cs
public static readonly IValueConverter SrcListConverter = WithOrder(
                Or(UrlConverter, FromParser(FromString(ParseLocal))),
                Or(FromParser(FromString(ParseFormat)), None))
            .FromList();

        public static String ParseLocal(this StringSource source)
        {
            if (source.IsFunction("local"))
            {
                var content = source.ParseString() ?? source.ParseIdent();
                var f = source.SkipGetSkip();

                if (content != null && f == Symbols.RoundBracketClose)
                {
                    return content;
                }
            }

            return null;
        }

        public static String ParseFormat(this StringSource source)
        {
            if (source.IsFunction("format"))
            {
                var content = source.ParseString() ?? source.ParseIdent();
                var f = source.SkipGetSkip();

                if (content != null && f == Symbols.RoundBracketClose)
                {
                    return content;
                }
            }

            return null;
        }
```

**Comment by FlorianRappl** [comment]
Good question - I think one of the reasons was that this can be fairly complicated and was therefore at the moment not implemented (but `src` should already be populated / regarded as valid).

We could also use your converter (but we need some more unit tests against at least the most common use cases, e.g., with local fonts, fonts from URLs, fonts from URLs with/without format, ...) - looks like a good solution!

Thanks for your efforts! 👍

**Comment by FlorianRappl** [comment]
Has landed in `devel`.
