### ISSUE TITLE
Accessing Styles with Relative Units

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp.Css#3]
See [AngleSharp #186](https://github.com/AngleSharp/AngleSharp/issues/186) for full discussion.

Relative units should just work in the CSSOM, however, with help of the `IRenderDevice` they should also be transformed to absolute units for any style computation.

**Comment by The-Nutty** [comment]
I have run up against this issue, would you accept a PR that would update Length.ToPixel https://github.com/AngleSharp/AngleSharp.Css/blob/f94b973c8862e2fdf1933bfc95f2c0f83cda0976/src/AngleSharp.Css/Values/Primitives/Length.cs#L276 and CssValueExtentions.AsPx https://github.com/AngleSharp/AngleSharp.Css/blob/f94b973c8862e2fdf1933bfc95f2c0f83cda0976/src/AngleSharp.Css/Extensions/CssValueExtensions.cs#L44 to both accept a IRenderDevice.

That would allow you to calculate % based values you could then add a DefaultFontSize to IRenderDevice allowing you to calculate REM. Then the only problem is EM and im not sure thats do able without a full render tree. 

At first glance this looks reasonably simple is there something im missing or is this planned to be change to accommodate a render tree soon?

**Comment by FlorianRappl** [comment]
Yeah sounds reasonable at first - but as you said the render tree would also cover this somewhat.

I have to admit I wish I could dedicate more time for this (and have a render tree already...)...

Proposal from my side: Can we introduce an interface that holds something like current font-size, current width, current height (could anything else be relevant?). `IRenderDevice` could implement this interface, but also some other thing that is later used in a render tree computation could pass that on.

Such a PR would be superb and really appreciated 🚀 ?

**Comment by The-Nutty** [comment]
Yeah that sounds like a good solution from my point of view.

**Comment by FlorianRappl** [comment]
Hi @The-Nutty  - thanks for coming back here!

You still want to do the PR?

Then I could focus on the other backlog items for 0.14 and we could ship it sooner I think. Would be much appreciated :beers.!

**Comment by The-Nutty** [comment]
I can take a look but work is very busy at the moment so im not sure how much time i can dedicate.

What is the reason for another interface on top of render device (as render device currently contains height and width)?

**Comment by FlorianRappl** [comment]
> What is the reason for another interface on top of render device (as render device currently contains height and width)?

Well, because we only have a render device on the outside. Then inside we only have boxes. For computing a new box it does not make sense to duplicate all the properties of the render device.

Still such a box would be the usual input to this method. So this box needs only a more lightweight interface, which is then implemented by anything that may request a computation of the dimensions.

**Comment by The-Nutty** [comment]
Ok thanks, looking at it again, am i right in thinking in order to compute % values (and em to some extent) you need a full render tree as you need to know the width of your parent. Unless im missing something i think this would be harder than i anticipated.

**Comment by FlorianRappl** [comment]
> Ok thanks, looking at it again, am i right in thinking in order to compute % values (and em to some extent) you need a full render tree as you need to know the width of your parent. Unless im missing something i think this would be harder than i anticipated.

That's why we have only a single interface like `IRenderDimensions`, which would give you this info.

Again, we are not thinking in the whole tree. We are just thinking from the perspective of a single value. A single value would never inspect the whole tree, but only work against the information of the current local box. This is why I brought up this interface. And this is why having this interface makes sense later also for a render tree.

**Comment by The-Nutty** [comment]
Thanks for clearing that up, jsut to check we are on the same page i have added the interfaces but not test/logic/docs/style yet here https://github.com/The-Nutty/AngleSharp.Css/commit/895d19d13e3084889f34abffb787eb4f07fe6711 could you take a quick look through and check all looks good before i continue?

**Comment by FlorianRappl** [comment]
Landed in `develop` - thanks for the awesome contribution @The-Nutty !

Preview available - if no complaints / bug reports go in I would merge into `master` (i.e., release AngleSharp.Css 0.14.0) tomorrow.
