### ISSUE TITLE
CSS **boder-style** not properly expanded when 3 values are given.

### ISSUE THREAD

**Issue by atlastodor** [AngleSharp/AngleSharp.Css#34]
### Prerequisites

- [ Yes ] Can you reproduce the problem in a [MWE]
- [ Yes 0.12.1 ] Are you running the latest version of AngleSharp?
- [ Yes ] Did you check the FAQs to see if that helps you?
- [ Yes ] Are you reporting to the correct repository? (if its an issue with the core library, please report to `AngleSharp` directly)
- [ Yes ] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Description

CSS **boder-style** not properly expanded when 3 values are given.

### Steps to Reproduce

1. Configure AngleSharp WithCss.
2. Using a new BrowsingContext, parse this HTML:
```
<!DOCTYPE html>
<html>
<head><title></title></head>
<body style="border-style: hidden double dashed;"></body>
</html>
```
3. Get the style for the Body element.
`var styleDeclaration = document.Body.ComputeCurrentStyle();`

**Expected behavior:**
As per [CSS border-style
](https://developer.mozilla.org/en-US/docs/Web/CSS/border-style)
> When **three** values are specified, the first style applies to the **top**, the second to the **left and right**, the third to the **bottom**.
```
"border-top-style: hidden"
"border-left-style: double"
"border-right-style: double"
"border-bottom-style: dashed"
```

**Actual behavior:** 
```
"border-top-style: double"
"border-left-style: double"
"border-right-style: hidden"
"border-bottom-style: dashed"
```

**Environment details:** 
Windows 10, .Net 4.7

### Possible Solution
Fix the order into which the property is expanded.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
