### ISSUE TITLE
CSS shorthand property **text-decoration** is not properly expanded

### ISSUE THREAD

**Issue by atlastodor** [AngleSharp/AngleSharp.Css#35]
### Prerequisites

- [ Yes ] Can you reproduce the problem in a [MWE]
- [ Yes 0.12.1 ] Are you running the latest version of AngleSharp?
- [ Yes ] Did you check the FAQs to see if that helps you?
- [ Yes ] Are you reporting to the correct repository? (if its an issue with the core library, please report to `AngleSharp` directly)
- [ Yes ] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Description

CSS shorthand property **text-decoration** is not properly expanded.

### Steps to Reproduce

1. Configure AngleSharp WithCss.
2. Using a new BrowsingContext, parse this HTML:
```
<!DOCTYPE html>
<html>
<head><title></title></head>
<body style="text-decoration: underline dotted;"></body>
</html>
```
3. Get the style for the Body element.
`var styleDeclaration = document.Body.ComputeCurrentStyle();`

**Expected behavior:**
As per [CSS text-decoration
](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)
> <'text-decoration-line'> || <'text-decoration-style'> || <'text-decoration-color'>.
```
"text-decoration-style: dotted"
"text-decoration-line: underline"
```

**Actual behavior:** 
```
"text-decoration-style: underline"
"text-decoration-line: dotted"
```

**Environment details:** 
Windows 10, .Net 4.7

### Possible Solution
Swap so **text-decoration-style** is expanded into **text-decoration-line** and vice-versa.

PS: When you are changing CSS properties behavior, could you please override the **ToString()** method to return the **CssText**. This will make working in the debugger much easier.

**Comment by FlorianRappl** [comment]
Thanks for the report. I'll look into it.

> PS: When you are changing CSS properties behavior, could you please override the ToString() method to return the CssText. This will make working in the debugger much easier.

Unfortunately, this was one of the original designs and it has many pitfalls. What I can recommend is either working with some auto variables or something like OzCode.

Just for debugging reasons `ToString` should not be overridden. Instead, `DebuggerDisplayAttribute` could be used in such cases (which was already used in AngleSharp in earlier versions; but as explained we discarded that). One of the reasons not to use it in AngleSharp (and AngleSharp.Css) is that this output (W3C serialization) may be confusing at times and does not tell the whole story (e.g., two classes may be have the same serialization).

**Comment by FlorianRappl** [comment]
Landed in `devel`.

**Comment by atlastodor** [comment]
> Just for debugging reasons ToString should not be overridden. Instead, DebuggerDisplayAttribute could be used in such cases (which was already used in AngleSharp in earlier versions; but as explained we discarded that). One of the reasons not to use it in AngleSharp (and AngleSharp.Css) is that this output (W3C serialization) may be confusing at times and does not tell the whole story (e.g., two classes may be have the same serialization).

OK. I understand. Normally when I need such a thing, my method will return something like:
`ToString() => this.GetType().Name + ": " + this.MyName;`
… so that the object can easily be debugged, but users won't confuse **ToString** with something returning useful information.

**Comment by FlorianRappl** [comment]
This sounds like a great strategy @atlastodor. I guess we could do something like this!
