### ISSUE TITLE
CssUriParser - wrong variable used in condition

### ISSUE THREAD

**Issue by zeaposs** [AngleSharp/AngleSharp.Css#36]
Hi there, I think I've found a small bug while reading code:
https://github.com/AngleSharp/AngleSharp.Css/blob/e59a6e7d9afd2ee716f0a5a7c0535cfc0e9001c7/src/AngleSharp.Css/Parser/Micro/CssUriParser.cs#L210

I think this should be `else if (current == Symbols.CurlyBracketOpen)`. Sorry for not doing a PR.

**Comment by FlorianRappl** [comment]
I think you are right there - mind if you make a PR? Otherwise I'll fix the bug in the near future.

Thanks!

**Comment by zeaposs** [comment]
You want that PR on master or on devel? And will you be on gitter? I have one question about parser :) .

**Comment by FlorianRappl** [comment]
Sure I'm on Gitter - and yes - always use `devel` as target (once merged a preview build is automatically released). Thanks for asking!

**Comment by FlorianRappl** [comment]
Landed in `devel`.

Thanks for your contribution :beers:!
