### ISSUE TITLE
A friendly ToString() for  cssstylerule

### ISSUE THREAD

**Issue by git-net** [AngleSharp/AngleSharp.Css#43]
seems SelectorText maybe a good choice.

**Comment by FlorianRappl** [comment]
Hm any reason for this? Just asking because this will impact all users and we did not override the `ToString` for a reason.

Is the `DebuggerDisplayAttribute` (i.e., defining how it looks while debugging / inspecting) what you are after?

**Comment by git-net** [comment]
yes，use for debug

**Comment by git-net** [comment]
by the way 。how to adjust  Selector type，eg TypeSelector。。。？

**Comment by FlorianRappl** [comment]
The selector type comes from the parsed selector - it is strongly bound to the used selector and cannot be changed. If you need a new selector you'll need to parse the string / or construct it manually.

For debugging purposes I'll think about a proper solution. Maybe decorating the class with the DebuggerDisplayAttribute makes sense; just not sure if it should only be the selector or something else, too.

**Comment by FlorianRappl** [comment]
Landed in `devel` and the preview.
