### ISSUE TITLE
GetInnerText does not work

### ISSUE THREAD

**Issue by wuyu8512** [AngleSharp/AngleSharp.Css#44]
``
var doc = new HtmlParser().ParseDocument("<HTML><BODY><div>1<br/>2</div></BODY></HTML>");
Console.WriteLine(doc.DocumentElement.GetInnerText());
``

I want to know what's wrong

**Comment by FlorianRappl** [comment]
Sorry more information needed.

**Comment by wuyu8512** [comment]
Thank you
This looks like my problem
Because i just write like this
