### ISSUE TITLE
linear-gradients are not written to css with angles

### ISSUE THREAD

**Issue by Fraaankes** [AngleSharp/AngleSharp.Css#45]
# Bug Report

## Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Parsing a style rule with a linear-gradient, and then writing the same rule back to css causes the angle to get removed.

## Steps to Reproduce

```
class Program
    {
        static void Main(string[] args)
        {
            var parser = new CssParser();
            var styleSheet = parser.ParseStyleSheet(".bg { background-image: linear-gradient(to right, #FF866E 0, #F15A24 0); }");
            var css = styleSheet.ToCss();
            Console.WriteLine(css);
            // Outputs
            // .bg { background-image: linear-gradient(rgba(255, 134, 110, 1) 0, rgba(241, 90, 36, 1) 0) }
        }
    }
```

**Comment by FlorianRappl** [comment]
Awesome thanks for the report and ...

... :tada: even more appreciate the PR :heart:!

:beers: :beers: Thanks!

**Comment by FlorianRappl** [comment]
Landed in the preview! Available in `devel`.

**Comment by jogibear9988** [comment]
@FlorianRappl is there a preview nuget?
