### ISSUE TITLE
Exception regarding "iso-2022-cn" encoding

### ISSUE THREAD

**Issue by UweKeim** [AngleSharp/AngleSharp.Css#47]
I'm currently migrating from Alba.Css to AngleSharp.Css.

Having this code:

```cs
var parser = new CssParser();
parser.ParseStyleSheet(".dummy { font-family: 'Poiret One' }");
```

I'm running it on a German Windows 10, 64-bit inside a .NET 4.7.2 WinForms application.

I'm getting this error:

> System.ArgumentException: '"iso-2022-cn" ist kein unterstützter Codierungsname. Informationen zum Definieren einer benutzerdefinierten Codierung entnehmen Sie der Dokumentation zur Encoding.RegisterProvider-Methode.
Parametername: name'

The stack trace contains one item only:

>    at System.Globalization.EncodingTable.internalGetCodePageFromName(String name)

The error occurs in the last line (`ParseStyleSheet`) of my code snippet.

I honestly do not unserstand where the strange encoding is pulled from.

What I assume is that _maybe_ I have to register some "global" settings to AngleSharp.Css, but I found nothing in detail that I should call.

### My question

What am I doing wrong here, and how can I solve this?

**Comment by FlorianRappl** [comment]
Have you looked at: https://github.com/AngleSharp/AngleSharp/issues/839?

If you use AngleSharp 0.13 then try to go to the 0.14 preview; the fix above is implemented there. Let me know if it works or does not work. Thanks!

**Comment by UweKeim** [comment]
I've now upgraded AngleSharp to 0.14, but found no preview NuGet package for AngleSharp**.Css**.

With only AngleSharp upgraded to 0.14, the error still exists.

Any chance to get AngleSharp.Css as a preview package on NuGet, too?

**Comment by FlorianRappl** [comment]
They should be compatible - can you just edit your app bindings to forward 0.13 to the 0.14 preview package?

**Comment by UweKeim** [comment]
So "AngleSharp.Css" is completely contained within "AngleSharp"?

That confuses me completely 😕 

I'll think best for now is to stick with Alba.Css and wait until stable AngleSharp.Css is out there. This way, no pressure for both sides.

**Comment by FlorianRappl** [comment]
Hm I think you misunderstood?

> So "AngleSharp.Css" is completely contained within "AngleSharp"?

Why should that be? AngleSharp.Css has a dependency on AngleSharp like AngleSharp has a dependency on .NET/Core. That does not mean that one contains the other.

> I'll think best for now is to stick with Alba.Css and wait until stable AngleSharp.Css is out there. This way, no pressure for both sides.

You can do as you like, but that will presumably not fix your issue. Just make a binding redirect instead of having both installed.

**Comment by UweKeim** [comment]
Since my app.config tells me that there _is_ already a binding redirect and still the error occurs, I'm more confused than ever.

      <dependentAssembly>
        <assemblyIdentity name="AngleSharp" publicKeyToken="e83494dcdc6d31ea" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-0.14.0.0" newVersion="0.14.0.0" />
      </dependentAssembly>

Anyway, thanks a lot for your fast reply (as always) and the nice libraries. I love them a lot.

**Comment by FlorianRappl** [comment]
I am confused here, too. Can you check if AngleSharp itself works (maybe its just a thing with the binding redirect here; maybe it cannot work in the given case). I would love to understand if its indeed this bug or if a pre-release of AngleSharp.Css 0.14 would fix this.

**Comment by UweKeim** [comment]
Shame on me:

The error occurs in `HtmlParser` and `CssParser`, too.

It seems though, that this is just a [first-chance-exception](https://stackoverflow.com/q/564681/107625) that is caught internally.

So to summarize:

- Using 0.14
- Error occurs
- Does not bubble up to the caller

I don't know how much performance impact this causes, I'll give it to my users and see whether they complain.

**Comment by FlorianRappl** [comment]
Unfortunately, there is (or maybe was / but then at least is not available to us) no way to detect what encodings are supported or not. This is why we just get the encodings and catch exceptions here (internally).

We always have a proper fallback (usually UTF8, but for some exotic encodings it may be different / more suitable).

The default selection of exception handling in VS can make this tricky. Thanks for your patience.

Just let me know if anything else is fishy. Thanks! :beers:

**Comment by UweKeim** [comment]
Thanks for _your_ patience!

Maybe an optional option to explicitely specify an encoding (`UTF-8` in my case) could speed things up a little bit.

Herzliche Grüße nach München 🥨🍺🎡

**Comment by FlorianRappl** [comment]
> Maybe an optional option to explicitely specify an encoding (UTF-8 in my case) could speed things up a little bit.

Good point - yes indeed. I think you can already override the encoding selection, but you cannot override the actually used encodings.

Grüße zurück nach Ulm! :beers:
