### ISSUE TITLE
New Release or preview (Nuget)?

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp.Css#48]
Would it be possible to release a new Version with the css gradient angle fix?

**Comment by FlorianRappl** [comment]
This is coming later today or tomorrow.

Sorry for the late reply.

**Comment by FlorianRappl** [comment]
Alpha is out there on [NuGet](https://www.nuget.org/packages/AngleSharp.Css/0.14.0-alpha-138).
