### ISSUE TITLE
Expose StyleCollectionExtensions publicly

### ISSUE THREAD

**Issue by The-Nutty** [AngleSharp/AngleSharp.Css#51]
# New Feature Proposal
Currently if you are calling CssApiExtensions.ComputeCurrentStyle for a large number of elements in a single document it can be very slow, by allowing the caller to cache the StyleCollection returned from window.GetStyleCollection in WindowExtensions.GetComputedStyle this operation can be speed up significantly. I believe this was mentioned in another issue but im unable to find it at current.

## Description

Is there a reason StyleCollectionExtensions cant be public, that would fix this issue as the caller could provide there own version of the WindowExtensions.GetComputedStyle with caching.

Would you be open to a PR that did this, if i have some spare time i may try to profile this code path further and see if there are any other easy wins.

## Background

If you need to walk the dom calculating the style of all/multiple elements. 

## Specification

N/A

**Comment by FlorianRappl** [comment]
Exposed `IStyleCollection` incl. all extensions for it.

Landed in `devel` and in the preview on NuGet.
