### ISSUE TITLE
StyleCollectionExtensions.SortBySpecificity does not account for null selector.

### ISSUE THREAD

**Issue by The-Nutty** [AngleSharp/AngleSharp.Css#52]
# Bug Report
I have observed instances where ICssStyleRule.Selector is null. This causes StyleCollectionExtensions.SortBySpecificity to throw a null reference exception.
## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Possible Solution

I unfortunately dont have the raw HTML that caused this issue but i have confirmed the following change does fix the issue.
```
            rules.Where(m => m.Selector?.Match(element) ?? false).OrderBy(m => m.Selector.Specificity);
```

Would you accept a PR for this solution?

**Comment by FlorianRappl** [comment]
I already pushed it! Thanks for investigating this - indeed it was an issue and the fix works like a charme! :beers:

Landed in `devel` and the preview.

**Comment by The-Nutty** [comment]
Brilliant thanks.
