### ISSUE TITLE
Make StyleCollectionExtentions.ComputeDeclarations take a IEnumerable<ICssStyleRule>to allow for caching of the StyleCollection.

### ISSUE THREAD

**Issue by The-Nutty** [AngleSharp/AngleSharp.Css#53]
# Bug Report
Iterating through IWindow.GetStyleCollection is slow if doing on multiple elements, this could be because _sheets is deferred or just because GetEnumerator is doing lots of work.
## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description
This relates to #51 where i was hoping to be able to cache the StyleCollection returned by IWindow.GetStyleCollection to significantly speed up the process of calling StyleCollection.ComputeDeclarations on every element in a document. However it is still just as slow.

## Possible Solution

1. Make ComputeDeclarations take a IEnumerable<ICssStyleRule> that could be pre calculated.
2. Optionally 1 but return a IEnumerable<ICssStyleRule> from IWindow.GetStyleCollection.

Im happy to implement the change if that would help as if possible i would appreciate it if we could get this out in a patch version, but wanted to run potential solutions by you before creating a PR.

**Comment by FlorianRappl** [comment]
> Im happy to implement the change if that would help as if possible i would appreciate it if we could get this out in a patch version, but wanted to run potential solutions by you before creating a PR.

Sure just make a PR and adjust the version to 0.14.1!
(https://github.com/AngleSharp/AngleSharp.Css/blob/master/src/Directory.Build.props and in the CHANGELOG)

**Comment by FlorianRappl** [comment]
Thanks for the superb contribution! I'll close the issue the update should be out in a bit.
