### ISSUE TITLE
Counters used in content css property are broken after calling ToCss

### ISSUE THREAD

**Issue by nazar554** [AngleSharp/AngleSharp.Css#58]
# Bug Report

## Description

After parsing a CSS stylesheet with `counter()` call inside `content:` property, `ToCss()` returns invalid CSS.

## Steps to Reproduce

```csharp
var parser = new CssParser();
var sheet = parser.ParseStyleSheet(@"
h1::before {
  counter-increment: h1;
  content: counter(h1) "".\00A0"";
}
");
var css = sheet.ToCss();
```

**Expected behavior:**
`h1::before { counter-increment: h1 1; content: counter(h1)  ". " }`
**Actual behavior:** 
`h1::before { counter-increment: h1 1; content: h1 decimal  ". " }`

**Environment details:** [OS, .NET Runtime, ...] .NET 4.8/Windows 10 AngleSharp.Css 0.14.1

**Comment by FlorianRappl** [comment]
Thanks for the report!

A fix is available in 0.14.2.
