### ISSUE TITLE
background: none not parsed correctly

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp.Css#65]
If an inline style contains `background: none` it is silently omitted from the parsed style.

```c#
var parser = new HtmlParser(new HtmlParserOptions(), BrowsingContext.New(new Configuration().WithCss()));
var html = "<html><body><section style=\"border-top-width: 1px; background: none\"></section></body></html>";
var doc = parser.ParseDocument(html);
var section = doc.Body.FirstElementChild;
var style = section.GetStyle();
```

`style.Declarations` contains only `border-top-width`. If the CSS contains `background-image: none` it works. Same for other background properties if you use an initial value such as `background: repeat`. In the latter case, `style.Declarations` contains all longhand background properties such as `background-position-x: initial` etc.

If the CSS contains other background properties along with `none`, they are also dropped completely, for example `background: none rgb(1, 2, 3)` will be ignored.

**Comment by FlorianRappl** [comment]
Thanks for the report - I think this can be fixed quite fast.
