### ISSUE TITLE
CSS parser cannot parse some keyword values for `width` (max-content, min-content, fit-content)

### ISSUE THREAD

**Issue by meziantou** [AngleSharp/AngleSharp.Css#69]
# Bug Report

## Description

Anglesharp is unable to parse `width: fit-content` property

## Steps to Reproduce

````
using System;
using AngleSharp.Css.Dom;
using AngleSharp.Css.Parser;

var options = new CssParserOptions()
{
    IsIncludingUnknownDeclarations = true,
    IsIncludingUnknownRules = true,
    IsToleratingInvalidSelectors = true,
};
var parser = new CssParser(options);
var sheet = parser.ParseStyleSheet("div{width: fit-content;}"); // https://developer.mozilla.org/en-US/docs/Web/CSS/width

foreach (var rule in sheet.Rules)
{
    Console.WriteLine(((ICssStyleRule)rule).Style.GetWidth()); // ""
    Console.WriteLine(rule.CssText); // div { }
}
````

**Expected behavior:** [What you expected to happen]

It correctly parses the value and `rule.CssText` .

**Actual behavior:** [What actually happened]

`rule.CssText` doesn't contains the `width` property.

**Environment details:** [OS, .NET Runtime, ...]

Windows 20H1, .NET 6 preview 3

## Possible Solution

Width should use a new value converter instead of `AutoLengthOrPercentConverter` to accept more keyword values (`fit-content`, `max-content`, `min-content`). It seems `fit-content` is also a function (e.g. `fit-content(20em)`)

- https://developer.mozilla.org/en-US/docs/Web/CSS/width
- https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content()

**Comment by FlorianRappl** [comment]
This is hardly a bug - rather a new feature request. Keep in mind that the web continuously evolves and implementations are always behind.

That being said - contributions are welcome!

**Comment by meziantou** [comment]
I've created a PR, but I'm clearly not sure of the sizing enum. Feel free to comment on the PR :)

https://github.com/AngleSharp/AngleSharp.Css/pull/70

**Comment by FlorianRappl** [comment]
Its a great PR - much appreciated! Will release a 0.15.1 soon.
