### ISSUE TITLE
Allow css to be used to style xml

### ISSUE THREAD

**Issue by drowbury** [AngleSharp/AngleSharp.Css#73]
# New Feature Proposal
Css can be used to style xml per [w3](https://www.w3.org/TR/xml-stylesheet/)

## Description

From running the code with my own project just by treating the IXmlElements the same as IHtmlElements and ISvgElements the style is applied. 

## Background

Allowing xml to be styled by css provides more flexibility.

## Specification

Css should be able to be applied to xml

**Comment by FlorianRappl** [comment]
Sorry for me this one is quite unclear; shouldn't this issue be rather a story for `AngleSharp.Xml`? How should this look like?

By spec, XML remains unstyled.
