### ISSUE TITLE
Parsing or setting style attributes with [out of range values] should not throw exceptions

### ISSUE THREAD

**Issue by atefshehata** [AngleSharp/AngleSharp.Css#8]
Thanks for creating this excellent project. I really like it.

When using CssEngine, some of the websites I try to load throw OverflowException: Value was either too large or too small for an (Int32, ...).

The parser throws this error and ignores the rest of the style sheet.

Here is a shortened call stack where the error happens: (sorry, the call stack is to large to paste it here)
AngleSharp.Parser.Css.CssNumberToken.get_IntegerValue()
...
...
AngleSharp.Parser.Css.CssParser.ParseStylesheetAsync()

Practically, web browsers treat this errors in more relaxed mode and they don't throw any exceptions; they check the supplied value and set either the maximum or the minimum for the given data type. The same also applies for setting style values directly using CSSStyleDeclaration class

for example, the following script tries to set zIndex with too large value.

var elm=document.getElementById('ID');
elm.style.zIndex='99999999999999999999999999999999999999999';
elm.style.zIndex;

If you run this script in debugger console of any web browser you will get the maximum value of Int32 "2147483647"

While setting too small value like the following example:

elm.style.zIndex='-99999999999999999999999999999999999999999';
will return the minimum value of Int32 "-2147483648"

So, does AngleSharp has any option to control whether to automatically convert out of range values or to throw exceptions (maybe something like strict mode). I'm talking about configuration option because I didn't read the specifications of parsing CSS style sheets and I don't want you to break any specs. But if the specs allow automatic conversion then there is no need for any option and the conversion should be applied automatically.

Thanks and good luck,
Atef

**Comment by zastrowm** [comment]
Just encountered this as well; I believe the css in my case was.

```
div#preview-toolbar {
    z-index: 9999999999999
}
```

I presume that no progress has been made on this issue?

**Comment by FlorianRappl** [comment]
Yes, sorry, no progress was made. I am, however, currently trying to finish some things and give AngleSharp some focus again. My goal is to finally make v1 happen, which includes, of course, AngleSharp.Css (and hopefully, but not necessarily, AngleSharp.Scripting).

I don't want to promise too much yet. But I am still here and I never gave up on AngleSharp!
