### ISSUE TITLE
Question aboute Minification of CSS

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp.Css#89]
As I worked on #88 for #85 I found that MinifyStyleFormatter does not combine that attribute.

But with that, I wanted to know, is it intended that MinifyStyleFormater should do this, or should it only write css without beautification?

If so, what's the best way to do it? Should I create a own formater, or is this the wrong place?

**Comment by FlorianRappl** [comment]
Right now this is only about CSS without beautification. There is, however, no rule that states that the existing implementation cannot be improved / extended.

If your desired output is too specific we can either put the additional behavior behind options or you'd need to create your own formatter.

**Comment by jogibear9988** [comment]
Do you have a good idea where to put the minification?

I've created an example https://github.com/AngleSharp/AngleSharp.Css/pull/93
but I'm not sure if that's best way to do. The method could get very huge

**Comment by jogibear9988** [comment]
https://github.com/node-projects/web-component-designer/blob/master/src/elements/helper/CssCombiner.ts
