### ISSUE TITLE
Add content-visibility CSS Property

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp.Css#90]
# New Feature Proposal

## Description

from css spec: https://www.w3.org/TR/css-contain-2/#content-visibility

## Background

Provide any additional background for the feature. e.g., user scenarios.

## Specification

In case of updates that adhere to specification changes, please reference the used specification.

**Comment by jogibear9988** [comment]
I thought I could do this, but I've one question.

In Map.cs:

        /// <summary>
        /// Contains the string-Visibility mapping.
        /// </summary>
        public static readonly Dictionary<String, Visibility> ContentVisibilities = new Dictionary<String, Visibility>(StringComparer.OrdinalIgnoreCase)
        {
            { CssKeywords.Visible, Visibility.Visible },
            { CssKeywords.Hidden, Visibility.Hidden },
            { CssKeywords.Collapse, Visibility.Collapse },
        };

is this allowed, or do we need to add an extra ContentVisibility enum to DOM at first?
Cause at the moment the Values are the same, but maybe they would differ in some time?
Whats the correct way to do it.

**Comment by FlorianRappl** [comment]
> Whats the correct way to do it.

Super-correct way is to introduce a new enum as suggested, however, in the given case I'd say it is not necessary. You can decide if you want to have the new enum or if you reuse the existing one.
