### ISSUE TITLE
Outlook does not support rgba

### ISSUE THREAD

**Issue by borgsoftwaresystems** [AngleSharp/AngleSharp.Css#96]
I'm currently using HTMLSanitizer which in turn uses AngleSharp. We are trying to sanitize code for use in emails but AngleSharp is converting the folllowing:

`<p style="background-color:#bbbbbb">`
or:
`<p style="background-color: rgb(187, 187, 187)">`

into:
`<p style="background-color: rgba(187, 187, 187, 1)`

The problem is that Outlook (for whatever reason) still does not support rgba. 

Could you please tell me if there is a way for me to tell AngleSharp to stop converting to rgba? If not, would you consider (if possible) providing a mechanism to support this?

Best regards,
Steve

**Comment by FlorianRappl** [comment]
Transferred!

**Comment by FlorianRappl** [comment]
Part of the next preview (incoming) via the `Color.UseHex` property.

**Comment by mganss** [comment]
The `Color` struct is private.

**Comment by spassarop** [comment]
This seems to keep the color format fixed. Is there a way to detect the color format when parsing the style? So hex stays hex and the same for rgb/a after a `ParseStyleSheet` call.

**Comment by FlorianRappl** [comment]
> Is there a way to detect the color format when parsing the style?

I think right now there is no such way.
